# ==============================================================================
# Audio2Tekst - Production Docker Compose Override
# ==============================================================================
#
# Production-specific configuration for Audio2Tekst
# 
# Usage:
#   docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
#
# ==============================================================================

version: '3.8'

services:
  audio2tekst:
    # Production-specific environment variables
    environment:
      # Enhanced security settings
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
      
      # Production logging
      - LOG_LEVEL=WARNING
      
      # Performance optimizations
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_GLOBAL_DEVELOPMENT_MODE=false
    
    # Production resource limits
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '1.0'
          memory: 2G
      
      # Restart policy for high availability
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
    # Production logging with rotation
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    
    # Health check with tighter intervals for production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
