[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
remove_redundant_aliases = true
force_sort_within_sections = true
combine_as_imports = true
skip_gitignore = true

# Eliminuje powielanie importów
no_lines_before = "LOCALFOLDER"
force_single_line = false

[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
